apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
spec:
  serviceName: timescaledb
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: timescaledb
          image: timescale/timescaledb-ha:pg17
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: timescaledb-pg-creds
                  key: pg_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescaledb-pg-creds
                  key: pg_password
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: timescaledb-pvc
          securityContext:
            runAsUser: 1000
          # readinessProbe:
          #   exec:
          #     command:
          #     - pg_isready
          #     - -U
          #     - $POSTGRES_USER
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
      volumes:
        - name: timescaledb-pvc
          persistentVolumeClaim:
            claimName: timescaledb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
spec:
  selector:
    app: timescaledb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
