# Generated by Django 4.2 on 2025-04-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_organization_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=64)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('list', 'List'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete')], max_length=32)),
            ],
            options={
                'unique_together': {('resource_type', 'operation')},
            },
        ),
    ]
