# Generated by Django 4.2 on 2025-05-02 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_role_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
