# Generated by Django 5.2 on 2025-05-10 20:31

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=32)),
                ('identifier', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('measuring_type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float')], default='string', max_length=8)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('additional_info', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('upper_limit', models.FloatField(null=True)),
                ('lower_limit', models.FloatField(null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
    ]
