# Generated by Django 4.2 on 2025-05-02 05:59

from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('additional_info', django.contrib.postgres.fields.hstore.HStoreField()),
                ('upper_limit', models.FloatField(null=True)),
                ('lower_limit', models.FloatField(null=True)),
            ],
        ),
    ]
