# Generated by Django 4.2 on 2025-05-02 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('sensor_uid', models.UUIDField()),
                ('value', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'sensor_reading',
                'unique_together': (('timestamp', 'sensor_uid'),),
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='measuring_type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float')], default='string', max_length=8),
        ),
    ]
