# Generated by Django 5.2 on 2025-05-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('pk', models.CompositePrimaryKey('sensor_uid', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('sensor_uid', models.UUIDField()),
                ('value', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'sensor_reading',
            },
        ),
        migrations.RunSQL(
            """
            SELECT create_hypertable('sensor_reading', 'timestamp', create_default_indexes => FALSE);
            CREATE INDEX ON sensor_reading (timestamp, sensor_uid);
            ALTER TABLE sensor_reading DROP CONSTRAINT sensor_reading_pkey;
            """,
            migrations.RunSQL.noop,
        ),
    ]
