# Generated by Django 4.2 on 2025-05-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensorreading_sensor_identifier_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE sensor_reading DROP CONSTRAINT sensor_reading_pkey;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE sensor_reading ADD PRIMARY KEY (timestamp, sensor_uid);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "SELECT create_hypertable('sensor_reading', 'timestamp');",
            reverse_sql="DROP TABLE sensor_reading;"
        )
    ]
