# Generated by Django 4.2 on 2025-05-02 06:31

from django.db import migrations
from django.db.backends.postgresql.schema import BaseDatabaseSchemaEditor



class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensorreading_sensor_measuring_type'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT create_hypertable('sensor_reading', 'timestamp');",
            reverse_sql="DROP TABLE sensor_reading;"
        )
    ]
