# Generated by Django 4.2 on 2025-05-02 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('sensor', '0003_create_sensor_reading_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device'),
        ),
    ]
