# Generated by Django 4.2 on 2025-05-02 07:36

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_sensor_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='additional_info',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
