# Generated by Django 4.2 on 2025-05-02 07:48

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_sensor_add_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='additional_info',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
