# Generated by Django 5.2 on 2025-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="brand",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="serial_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
